### ISSUE TITLE
Create Buttons styling in Header component

### ISSUE THREAD

**Issue by BajraYeJoon** [BajraYeJoon/nepa.ly#1]
- Change </p> tag in header__right and change it to button
- Button when hovered color should change 
- add a phone icon side to Call Now

**Comment by vodoanhuy301** [comment]
Hey! Can I help you? I'm a ReactJs beginner, but I want to try!

**Comment by BajraYeJoon** [comment]
@vodoanhuy301  YES you can do it. Good Luck 🎯
