### ISSUE TITLE
Buttons are not showing when deployed to Netlify

### ISSUE THREAD

**Issue by BajraYeJoon** [BajraYeJoon/nepa.ly#4]
- after running npm run build, Buttons are not showing when run through serve -s build

**Comment by BajraYeJoon** [comment]
@chwonseok  Can you check this issue?

**Comment by chwonseok** [comment]
@BajraYeJoon Hey sorry mate I saw notification too late 😅

I'm nor trying to check your issue now, but I don't know which buttons you are having as issue.

Could you tell me specifically, pls?

**Comment by BajraYeJoon** [comment]
This is how it should be shown after build

![Capture](https://user-images.githubusercontent.com/25260689/141932928-5ed56766-ba5b-4394-b047-b2ff1b7de66e.JPG)

but after build , the buttons in the bottom section throughout the page is not being shown

![caadf](https://user-images.githubusercontent.com/25260689/141933101-b77129aa-8920-4ceb-b138-a52b4fc62cb6.JPG)

**Comment by chwonseok** [comment]
Weird. On this [link](https://nepal-ly.herokuapp.com/), It does show me all the buttons well.

Am I seeing different page?

**Comment by BajraYeJoon** [comment]
Yes, I had deployed to heroku and it is showing as it should be . however, in netlify the problem is existing https://vajra-nepally.netlify.app/.  the above screenshot was from netlify. 

More confused 🧐😄

**Comment by chwonseok** [comment]
@BajraYeJoon :D I found the problem! Check the opacity of `.button` in CSS

It's set as 1% right now. You just need to change to 100% (probably)

**Comment by BajraYeJoon** [comment]
Yes the issue is solved 😃✔
